name: Maven Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run Checkstyle
        run: ./mvnw -B checkstyle:check --file pom.xml
      - if: ${{ github.ref == 'refs/heads/main' }}
        name: OWASP Dependency Check
        run: ./mvnw dependency-check:check
      - name: Sonar Scan
        run: ./mvnw initialize sonar:sonar -Dsonar.login=${{ env.SONAR_TOKEN }}
      - name: Build with Maven
        run: ./mvnw -B package --file pom.xml
